apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-flower
  name: celery-flower
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flower-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-flower
        app: flower-pod
    spec:
      containers:
      - args:
        - /bin/sh
        - /data/recruitment/flower.start.sh
        image: registry.cn-beijing.aliyuncs.com/ihopeit/django-recruitment:{{BUILD_NUMBER}}
        imagePullPolicy: Always
        name: recruit-flower
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
