# Generated by Django 3.2 on 2021-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default='2021-03-01', verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类')], default='这里填职位类别', verbose_name='职位类别'),
        ),
    ]
