# Generated by Django 3.2 on 2021-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
    ]
